apiVersion: v1
kind: Service
metadata:
  name: deployproof-postgresql
  labels:
    {{- include "deployproof.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: deployproof
    app.kubernetes.io/component: database
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
