apiVersion: v1
kind: Service
metadata:
  name: deployproof-api
  labels:
    {{- include "deployproof.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: deployproof
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
