image:
  repository: deployproof-api
  tag: dev
  pullPolicy: IfNotPresent

application:
  version: "0.1.0"
  sourceRevision: local
  imageDigest: unset

configuration:
  environment: certification
  customerRegion: lab-west
  featureMode: standard

service:
  nodePort: 30082

postgresql:
  image: postgres:17.6-alpine@sha256:ef257d85f76e48da1c64832459b59fcaba1a4dac97bf5d7450c77753542eee94
  database: deployproof
  user: deployproof
  existingSecret: deployproof-db
  passwordKey: password
  storage: 512Mi

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
